FROM ubuntu:18.04

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    cmake \
    gstreamer1.0-x \
    libgstrtspserver-1.0-dev \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-good \
    gstreamer1.0-libav \
    gstreamer1.0-tools \
    libopencv-core-dev \
    libopencv-imgproc-dev \
    libopencv-imgcodecs-dev \
    g++ \
    vim \
    ca-certificates \
    git \
    curl \
    gdb